_target_: pytorch_lightning.Trainer

gpus: 1

min_epochs: 1
max_epochs: 20
limit_train_batches: 5000
limit_val_batches: 100
log_every_n_steps: 200

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null
