_target_: src.models.iterative_module.IterativeModule
lr: 0.001
weight_decay: 0.0005

net:
  _target_: src.models.components.simple_cnn.SimpleCNN
  input_channels: 4
  hidden_layers: 4
  hidden_channels: 16
