_target_: src.models.distana_module.DistanaModule
lr: 0.001
weight_decay: 0.0005

net:
  _target_: src.models.components.distana.Distana
  input_channels: 4
  pre_layer_size: 16
  lat_size: 16
  lstm_hid_size: 16
  kernel_size: 3
  bias: true