_target_: src.models.resnet_module.ResnetModule
lr: 0.001
weight_decay: 0.0005

net:
  _target_: src.models.components.simple_resnet.SimpleResnet
  input_channels: 4
  resblocks: 4
  resblock_channels: 16
