FROM tensorflow/tensorflow:latest

#RUN apt-get update && apt-get install -y software-properties-common && \
#    add-apt-repository ppa:ubuntugis/ppa && apt-get update && \
#    apt-get install -y libgdal-dev g++ --no-install-recommends && \
#    apt-get clean -y

RUN mkdir -p /.config
RUN chmod 777 /.config
