# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - equation: gas_dynamics
  - cluster: default.yaml

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "default"
