# @package _global_

# specify here default training configuration
defaults:
  - _self_
  - cluster: default
  - log_dir: default

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "kube_scheduler"