# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: gas_dynamics
  - model: resnet.yaml
  - callbacks: default.yaml
  - logger: tensorboard.yaml # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: default.yaml
  - log_dir: default.yaml
  - cluster: default.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "default"

# passing checkpoint path is necessary
ckpt_path: /home/andi/Programming/Repositories/code-2022-neuralpde/logs/experiments/runs/pdenet/2022-05-14_10-14-07/checkpoints/epoch_000.ckpt
