job_name: neuralpde-${hydra:runtime.choices.model}-${hydra:runtime.choices.datamodule}
image: lsx-staff-registry.informatik.uni-wuerzburg.de/dulny/neuralpde-2022:latest
cpus: 16
memory: 32
use_gpu: False
script_path": train.py