_target_: src.utils.pde_generator.GenerationUtility

name: advection_diffusion

data_dir: ${data_dir}/toypdes/advection_diffusion # data_dir is specified in config.yaml

zero_levels: [0]

variables: [u]

verbose: true

params:
  scale: 0.1
  D: 0.001
  vx: 1
  vy: 1

complexities:
  train: 5
  val: 5
  test: 5

num_equations:
  train: 50
  val: 10
  test: 10

domain:
  x:
    min: 0
    max: 1
    points: 100
    points_low: 10
  y:
    min: 0
    max: 1
    points: 100
    points_low: 10
  t:
    min: 0
    max: 1000
    step: 1