_target_: src.utils.pde_generator.GenerationUtility

name: gas_dynamics

data_dir: ${data_dir}/toypdes/gas_dynamics # data_dir is specified in config.yaml

zero_levels: [2,2,0,0]

variables: [p, t, u, v]

verbose: true

params:
  scale: 0.002
  mu: 0.01
  k: 0.01
  gamma: 1
  M: 1

complexities:
  train: 5
  val: 5
  test: 5

num_equations:
  train: 50
  val: 10
  test: 10

domain:
  x:
    min: 0
    max: 1
    points: 100
    points_low: 10
  y:
    min: 0
    max: 1
    points: 100
    points_low: 10
  t:
    min: 0
    max: 1000
    step: 1